export const REQUEST_LOGIN = 'LOGIN/REQUEST_LOGIN'
export const REQUEST_LOGIN_START = 'LOGIN/REQUEST_LOGIN_START'
export const REQUEST_LOGIN_SUCCESS = 'LOGIN/REQUEST_LOGIN_SUCCESS'
export const REQUEST_LOGIN_FAILURE = 'LOGIN/REQUEST_LOGIN_FAILURE'

export const REQUEST_REG = 'REG/REQUEST_REG'
export const REQUEST_REG_START = 'REG/REQUEST_REG_START'
export const REQUEST_REG_SUCCESS = 'REG/REQUEST_REG_SUCCESS'
export const REQUEST_REG_FAILURE = 'REG/REQUEST_REG_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'
export const LOGIN_LOCALLY = 'LOGIN_LOCALLY'
