export const REQUEST_PROJECTS = 'PROJECTS/REQUEST_PROJECTS'
export const REQUEST_PROJECTS_START = 'PROJECTS/REQUEST_PROJECTS_START'
export const REQUEST_PROJECTS_SUCCESS = 'PROJECTS/REQUEST_PROJECTS_SUCCESS'
export const REQUEST_PROJECTS_FAILURE = 'PROJECTS/REQUEST_PROJECTS_FAILURE'

export const CREATE_PROJECT = 'PROJECTS/CREATE_PROJECT'
export const CREATE_PROJECT_START = 'PROJECTS/CREATE_PROJECT_START'
export const CREATE_PROJECT_SUCCESS = 'PROJECTS/CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = 'PROJECTS/CREATE_PROJECT_FAILURE'

export const REQUEST_PROJECT_BY_ID = 'PROJECTS/REQUEST_PROJECT_BY_ID'
export const REQUEST_PROJECT_BY_ID_START = 'PROJECTS/REQUEST_PROJECT_BY_ID_START'
export const REQUEST_PROJECT_BY_ID_SUCCESS = 'PROJECTS/REQUEST_PROJECT_BY_ID_SUCCESS'
export const REQUEST_PROJECT_BY_ID_FAILURE = 'PROJECTS/REQUEST_PROJECT_BY_ID_FAILURE'

export const SAVE_PROJECT = 'PROJECTS/SAVE_PROJECT'
export const SAVE_PROJECT_START = 'PROJECTS/SAVE_PROJECT_START'
export const SAVE_PROJECT_SUCCESS = 'PROJECTS/SAVE_PROJECT_SUCCESS'
export const SAVE_PROJECT_FAILURE = 'PROJECTS/SAVE_PROJECT_FAILURE'

export const REMOVE_PROJECT = 'PROJECTS/REMOVE_PROJECT'
export const REMOVE_PROJECT_START = 'PROJECTS/REMOVE_PROJECT_START'
export const REMOVE_PROJECT_SUCCESS = 'PROJECTS/REMOVE_PROJECT_SUCCESS'
export const REMOVE_PROJECT_FAILURE = 'PROJECTS/REMOVE_PROJECT_FAILURE'

export const SET_PROJECT = 'PROJECTS/SET_PROJECT'
export const CREATE_TASK = 'PROJECTS/CREATE_TASK'
